openapi: 3.0.0
info:
  title: Drripside API
  version: 1.0.0
  description: API documentation for Dripside.

paths:
  /api/v1/user:
    get:
      summary: Retrieve a list of users
      tags:
        - Users
      security:
        - bearerAuth: []
      parameters:
        - name: timestamp
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
        - name: role
          in: query
          schema:
            type: string
        - name: name
          in: query
          schema:
            type: string
        - name: username
          in: query
          schema:
            type: string
        - name: email
          in: query
          schema:
            type: string
        - name: phone
          in: query
          schema:
            type: string
        - name: deleted
          in: query
          schema:
            type: string
      responses:
        "200":
          description: List of users retrieved successfully
        "401":
          description: Unauthorized
    post:
      summary: Add a new user
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        description: User object that needs to be added
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User created successfully
        "401":
          description: Unauthorized

  /api/v1/user/profile:
    get:
      summary: Retrieve the user profile
      tags:
        - Users
      security:
        - bearerAuth: []
      responses:
        "200":
          description: User profile retrieved successfully
        "401":
          description: Unauthorized
    patch:
      summary: Update the user profile
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        description: User profile data to update
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User profile updated successfully
        "401":
          description: Unauthorized

  /api/v1/user/register:
    post:
      summary: Register a new user
      tags:
        - Users
      requestBody:
        description: User registration data
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                username:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: User registered successfully
        "400":
          description: Bad request

  /api/v1/user/login:
    patch:
      summary: Login a user
      tags:
        - Users
      requestBody:
        description: User login data
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
        "400":
          description: Bad request
        "401":
          description: Unauthorized
