import { IDefault, IResponseData, IAccountStatus } from '../index';

export enum AdminRoles {
  ADMIN = 'Admin',
  SUPER_ADMIN = 'SuperAdmin',
  DEVELOPER_ADMIN = 'DeveloperAdmin',
}

export interface IAdmin extends IDefault {
  code: string;
  name: string;
  username: string;
  password: string;
  phone: number;
  email: string;
  role: AdminRoles;
  status: IAccountStatus;
  lastUsed?: Date;
  lastSync?: Date;
  usedIPaddress: string[];
  lastPassword?: string;
  resetPasswordAccess?: Boolean;
  autoGeneratedPasswd?: Boolean;
  passwordChanged?: Boolean;
  passwordChangedAt?: Date;
}

export interface IGetAdminsResponse extends IResponseData {
  currentPage: number;
  results: IAdmin[];
  latestCount: number;
  totalCount: number;
  totalPages: number;
}

export interface IAdminResponse extends IResponseData {
  results: IAdmin;
}
